-- MySQL Script generated by MySQL Workbench
-- mié 21 oct 2020 13:52:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurantes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci ;
USE `restaurantes` ;

-- -----------------------------------------------------
-- Table `restaurantes`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `razon` VARCHAR(200) NULL,
  `ruc` VARCHAR(13) NULL,
  `telefono` VARCHAR(10) NULL,
  `imagen` VARCHAR(250) NULL,
  `direccion` VARCHAR(250) NULL,
  `email` VARCHAR(100) NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `cedula` VARCHAR(13) NULL,
  `direccion` VARCHAR(250) NULL,
  `telefono` VARCHAR(10) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(60) NULL,
  `tipo` INT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_usuario_empresa_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `restaurantes`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantes`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mesa_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `restaurantes`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantes`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `restaurantes`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantes`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `descripcion` LONGTEXT NULL,
  `imagen` VARCHAR(200) NULL,
  `precio` DECIMAL(2,10) NULL,
  `estado` TINYINT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_menu_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `restaurantes`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantes`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes`.`orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `fecha` DATE NULL,
  `estado` TINYINT NULL,
  `usuario_id` INT NOT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_orden_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_orden_menu1_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `restaurantes`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurantes`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
